#!/bin/sh

mvn clean install

(
  cd /Users/jvanzyl/js/presto/presto
  prestoVersion=$(./mvnw --quiet help:evaluate -Dexpression=project.version -DforceStdout)
  ./mvnw clean install -DskipTests -TC3
  (
    cd presto-server/target/presto-server-${prestoVersion}
    cp -r /Users/jvanzyl/js/presto/etc .
    sudo bin/launcher run
  )
)
